name: Linux Build

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: sudo apt update && sudo apt install ninja-build lld-8 gperf libgcrypt20 libgcrypt20-dev

      - name: Download UltralightCore
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow: linux.yml
          workflow_conclusion: success
          name: ultralight-core
          path: deps/UltralightCore
          repo: InsigniaRSPS/UltralightCore-src

      - name: Download WebKitLibraries
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.ACCESS_TOKEN}}
          workflow: linux.yml
          workflow_conclusion: success
          name: webkitlibraries
          path: deps/WebKitLibraries
          repo: InsigniaRSPS/WebCore-deps

      - name: Build WebCore
        run: ./make

      - name: Check if build exists
        run: [ ! -d "build/out" ] && exit 1

      - uses: actions/upload-artifact@v2
        with:
          name: webcore
          path: build/out/